HOST = 'www.instagram.com'
URL_HOME = 'https://www.instagram.com'
URL_SIGN_IN = 'https://www.instagram.com/accounts/login/ajax/'
URL_PRIVATE_PAGE = 'https://www.instagram.com/accounts/edit/'
URL_FEED = 'https://www.instagram.com/?__a=1'
